# Generated by Django 4.1.1 on 2022-10-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_alter_chegadas_chegada_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chegadas',
            name='chegada_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partidas',
            name='partida_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voos',
            name='chegada_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voos',
            name='partida_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
