# Generated by Django 4.1.1 on 2022-11-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_alter_chegadas_chegada_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voos',
            name='status',
            field=models.CharField(blank=True, choices=[('embarcando', 'embarcando'), ('cancelado', 'cancelado'), ('programado', 'programado'), ('taxiando', 'taxiando'), ('pronto', 'pronto'), ('autorizado', 'autorizado'), ('em voo', 'em voo'), ('aterrissado', 'aterrissado')], max_length=20, null=True),
        ),
    ]
