# Generated by Django 4.1.1 on 2022-11-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_alter_voos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chegadas',
            name='codigo',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chegadas',
            name='companhia_aerea',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partidas',
            name='codigo',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partidas',
            name='companhia_aerea',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
