# Generated by Django 4.1.1 on 2022-12-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_chegadas_codigo_chegadas_companhia_aerea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chegadas',
            name='status',
            field=models.CharField(blank=True, choices=[('embarcando', 'embarcando'), ('cancelado', 'cancelado'), ('programado', 'programado'), ('taxiando', 'taxiando'), ('pronto', 'pronto'), ('autorizado', 'autorizado'), ('em voo', 'em voo'), ('aterrissado', 'aterrissado')], max_length=20, null=True),
        ),
    ]
