# Generated by Django 4.1.1 on 2022-12-11 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0006_chegadas_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chegadas',
            name='chegada_prevista',
        ),
        migrations.RemoveField(
            model_name='chegadas',
            name='chegada_real',
        ),
        migrations.RemoveField(
            model_name='chegadas',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='chegadas',
            name='companhia_aerea',
        ),
        migrations.RemoveField(
            model_name='chegadas',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='chegadas',
            name='status',
        ),
        migrations.RemoveField(
            model_name='partidas',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='partidas',
            name='companhia_aerea',
        ),
        migrations.RemoveField(
            model_name='partidas',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='partidas',
            name='partida_prevista',
        ),
        migrations.RemoveField(
            model_name='partidas',
            name='partida_real',
        ),
        migrations.RemoveField(
            model_name='partidas',
            name='status',
        ),
        migrations.AddField(
            model_name='chegadas',
            name='voo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoramento.voos'),
        ),
        migrations.AddField(
            model_name='partidas',
            name='voo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoramento.voos'),
        ),
    ]
