# Generated by Django 4.1.1 on 2022-12-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0007_remove_chegadas_chegada_prevista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidas',
            name='voo',
        ),
        migrations.DeleteModel(
            name='Chegadas',
        ),
        migrations.DeleteModel(
            name='Partidas',
        ),
    ]
